model:
  - GIN
device:
  - cuda
batch_size:
  - 32
learning_rate:
  - 0.01
classifier_epochs:
  - 1000
hidden_units:  # Note: GIN add a first layer that simply adds up all node features
  - [32, 32, 32, 32]

optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 50
      gamma: 0.5
loss:
  - MulticlassClassificationLoss
train_eps:
  - true
l2:
  - 0.
aggregation:
  - mean
gradient_clipping:
  - null
dropout:
  - 0.5

shuffle:
  - True
resume:
  - False